name: create recipe runs for pr commit

on:
  pull_request_target:
    branches: main
    paths:
      - 'feedstock/**'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      FEEDSTOCK_SPEC: "${{ github.repository }}"
      HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
      PR_NUMBER: "${{ github.event.pull_request.number }}"
      IS_DEV: "${{ contains(github.event.pull_request.labels.*.name, 'dev') }}"
    steps:
      - name: dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PANGEO_FORGE_BOT_TOKEN }}
          repository: pangeo-forge/registrar
          event-type: pull-request-commit
          client-payload: '{"feedstock_spec": "${{ env.FEEDSTOCK_SPEC }}", "head_sha": "${{ env.HEAD_SHA }}", "pr_number": "${{ env.PR_NUMBER }}", "is_dev": "${{ env.IS_DEV }}"}'
